suitecrm:
  build: 7.2.1
  ports:
    - "8080:80"
  links:
    - "db"
  environment:
    DB_TYPE: mysql
    DB_MANAGER: MysqlManager
dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql
db:
  image: mariadb
  volumes_from:
    - dbdata
  environment:
    MYSQL_ROOT_PASSWORD: EvXTC3R7Sef5aB725hKv
    MYSQL_DATABASE: suitecrm
    MYSQL_USER: suitecrm
    MYSQL_PASSWORD: B3fyAKRyFpaMR5vyPMJz